app:
    image: "python:3.9"
    before_script:
        - apt-get update -qy
        - apt-get update
        - apt-get install -y wget unzip curl

        # Install or update Google Chrome
        - CHROME_VERSION="119.0.6045.105-1"
        # Install Google Chrome
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - dpkg -i google-chrome-stable_current_amd64.deb || apt --fix-broken install -y
        - google-chrome-stable --version

        - python --version
        - python -m venv venv
        - source venv/bin/activate
        - pip install -r requirements.txt
    stage: deploy
    script:
        - python3 scrapingSEI.py
        - mkdir .public
        - cp -r index.html .public
        - mv .public public
        - echo "Página acessível por meio de ${CI_PAGES_URL}/${PAGES_PREFIX}"
    artifacts:
        paths:
        - public