app:
    image: "python:3.9"
    before_script:
        - python --version
        - python -m venv venv
        - source venv/bin/activate
        - pip install -r requirements.txt
    stage: deploy
    script:
        - python3 scrapingSEI.py